baseurl = "http:/krolow.com.br/"
languageCode = "en-us"
title = "Vinícius Krolow"
theme = "krolow"

[author]
	name = "Vinícius Krolow"

[permalinks]
	# Permalink format for pages.
	page = "/:title/"

	post = "/post/:title/"
	til = "/til/:title/"

[params]

    colorscheme = "white"

    # Tagline; HTML accepted here. Keep it concise.
    tagline = "Full Stack Software Developer - \"Lets hurt the code\""

    # Footer; Markdown accepted here.
    footer = "Copyright 2015 &copy; Vinícius Krolow"

    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = "Default Page Description"
    keywords = "default,page,keywords"

    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    email = "mailto:krolow@gmail.com"
    github = "http://github.com/krolow"
    twitter = "http://twiter.com/krolow"
    linkedin = "https://us.linkedin.com/in/krolow"

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    ganalytics = "your-google-analytics-tracking-code"

[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = "/"
    weight     = 0

    [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about/"
    weight     = 1
